version: '3'

services:
  postgres-container:
    container_name: postgres-container
    restart: always
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myfamily10
      POSTGRES_DB: videostream-typescript

  app:
    container_name: docker-node-typescript
    restart: always
    build: .
    ports: 
      - '80:3000'
    depends_on:
      - postgres-container
    links:
      - postgres-container